#!/usr/bin/env python
from __future__ import print_function
from pygments import highlight
from pygments.lexers import get_lexer_for_filename
from pygments.formatters import HtmlFormatter
import argparse
import os 

source_path = os.path.relpath(os.path.dirname(__file__))

html_template = '''<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN"
   "http://www.w3.org/TR/html4/strict.dtd">

<html>
<head>
  <title></title>
  <meta http-equiv="content-type" content="text/html; charset=None">
  <link rel="stylesheet" href="{css}" type="text/css">
</head>
<body>
{content}
</body>
'''

parser = argparse.ArgumentParser(description='Performs syntax highlighting with Pygments using a custom css file.')
parser.add_argument('source', metavar='FILENAME', type=str,
                     help='Source filename.')
parser.add_argument('-o', dest='output', metavar='FILENAME',
                    default=None, help='Output filename. Prints to standard out if not specified')
parser.add_argument('-s', dest='style', metavar='FILENAME',
                    default=os.path.join(source_path, 'anglican.css'),
                    help='Style to use for syntax highlighting. May be a pygments builtin or CSS style sheet.')
parser.add_argument('-p', dest='prestyles', metavar='ATTRIBUTES',
                    default='font-family: Source Code Pro; font-size: 35px',
                    help='Inline styles to use for <pre> element.')

if __name__ == '__main__':
    args = parser.parse_args()
    lexer = get_lexer_for_filename(args.source)
    code = open(args.source, 'r').read()        
    if os.path.isfile(args.style):
        formatter = HtmlFormatter(full=False, prestyles=args.prestyles)
        div = highlight(code, lexer, formatter)
        html = html_template.format(css=args.style, content=div)
    else:
        formatter = HtmlFormatter(full=True, style=args.style, prestyles=args.prestyles)
        html = highlight(code, lexer, formatter)    
    if args.output:
        f = open(args.output, 'w')
        f.write(html)
        f.close()
    else:
        print(html)
